
Dimension of matrix: number of rows * number of columns

### Addition
* only matrices of same dimension can be added
$$
X=
\begin{bmatrix}
    8 & 6 & 9 \\
   10 & 1 & 10 \\
\end{bmatrix}
+
\begin{bmatrix}
    3 & 10 & 2 \\
    6 & 1  & -1 \\
\end{bmatrix}
=
\begin{bmatrix}
    11 & 16 & 9 \\
    10 & 1  & 10 \\
\end{bmatrix}
$$


### Scalar Multiplication

$$
3 \times
\begin{bmatrix}
    1 & 0 \\
    2 & 5 \\
    3 & 1 \\
\end{bmatrix}
=
\begin{bmatrix}
    3 &  0 \\
    6 & 15 \\
    9 &  3 \\
\end{bmatrix}
$$

### Matrix Vector Multiplication

* columns of matrix must match row of vector

<img src="./img/1.png" width="60%"/>

<img src="./img/2.png" width="60%"/>



### Matrix Matrix Multiplication

* Number of columns in first matrix must match number of rows in second matrix

$$
\begin{bmatrix}
    1 & 3 & 2 \\
    4 & 0 & 1 \\
\end{bmatrix}
\begin{bmatrix}
    1 &  3 \\
    0 &  1 \\
    5 &  2 \\
\end{bmatrix}
=
\begin{bmatrix}
    11 &  10 \\
     9 &  14 \\
\end{bmatrix}
$$

<img src="./img/3.png" width="60%"/>

### Matrix Properties

* $A \times B \ne B \times A$
* Matrix multiplication is associative
* Identity matrix, 1 * I = I * 1 = I
$
\begin{bmatrix}
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1 \\
\end{bmatrix}
$

* Matrix Inverse, only m x m matrix have inverse. $A(A^{-1}) = A^{-1}A = I$
$$
\begin{bmatrix}
    3 & 4 \\
    2 & 16 \\
\end{bmatrix}
\begin{bmatrix}
      0.4 & -0.1   \\
    -0.05 &  0.075 \\
\end{bmatrix}
=
\begin{bmatrix}
      1 & 0   \\
      0 & 1   \\
\end{bmatrix}
=
I_{2x2}
$$

### Matrix Transpose

* $B_{ij} = A_{ji}$

$
A=
\begin{bmatrix}
   1  &  2  &  0 \\
   3  &  5  &  9
\end{bmatrix}
A^{T}=
\begin{bmatrix}
   1  &  3  \\
   2  &  5  \\
   0  &  9
\end{bmatrix}
$


In [1]:
import numpy as np
X = np.array([[1,0],
              [2,5],
              [3,1]])

In [3]:
# Scalar Multiplication
print X * 3

[[ 3  0]
 [ 6 15]
 [ 9  3]]


In [13]:
# Matrix Vector Multiplication
y = np.array([[1],
              [5],])

print X.dot(y)

print X * y.T # need to sum up the columns


[[ 1]
 [27]
 [ 8]]
[[ 1  0]
 [ 2 25]
 [ 3  5]]


In [3]:
import numpy as np
a = np.array([1,1,0])
b = np.array([0,1,1])
np.dot(a,b)

1

In [4]:
a = np.array([[9, 5], [6, 1]])
b = np.array([[3, 2], [5, 2]])

np.dot(a, b)



array([[52, 28],
       [23, 14]])

In [5]:
np.multiply(a, b)

array([[27, 10],
       [30,  2]])

In [1]:
2 + 2

4

In [3]:
import tensorflow

ImportError: No module named tensorflow