http://cs231n.github.io/optimization-2/

In [1]:
import numpy as np

w0 = 2
w1 = -3
w2 = -3
x0 = -1
x1 = -2

w0x0 = w0 * x0
w1x1 = w1 * x1

w0x0w1x1 = w0x0 + w1x1
dot = w0x0w1x1 + w2
ndot = -1 * dot
expndot = np.exp(ndot)
expndotp1 = 1 + expndot
invdot = 1 / expndotp1

print 'w0x0', w0x0
print 'w1x1', w1x1
print 'w0x0w1x1', w0x0w1x1
print 'dot', dot
print 'ndot', ndot
print 'expndot', expndot
print 'expndotp1', expndotp1
print 'invdot', invdot


w0x0 -2
w1x1 6
w0x0w1x1 4
dot 1
ndot -1
expndot 0.367879441171
expndotp1 1.36787944117
invdot 0.73105857863


In [20]:

# dinvdot = 1
dexpndotp1 = -1 / expndotp1 ** 2
dxpndot = dexpndotp1
dndot = dxpndot * np.exp(ndot)
ddot = dndot * -1
dw2 = ddot * 1
dw0x0w1x1 = ddot * 1
dw0x0 = dw0x0w1x1 * 1
dw1x1 = dw0x0w1x1 * 1
dw1 = dw1x1 * x1
dx1 = dw1x1 * w1
dw0 = dw0x0 * x0
dx0 = dw0x0 * w0


print 'dexpndotp1', dexpndotp1
print 'dexpndot', dexpndot
print 'dxpndot', dxpndot
print 'dndot', dndot
print 'ddot', ddot
print 'dw2', dw2
print 'dw0x0w1x1', dw0x0w1x1
print 'dw0x0', dw0x0
print 'dw1x1', dw1x1
print 'dw1', dw1
print 'dx1', dx1
print 'dw0', dw0
print 'dx0', dx0



dexpndotp1 -0.534446645389
dexpndot -0.534446645389
dxpndot -0.534446645389
dndot -0.196611933241
ddot 0.196611933241
dw2 0.196611933241
dw0x0w1x1 0.196611933241
dw0x0 0.196611933241
dw1x1 0.196611933241
dw1 -0.393223866483
dx1 -0.589835799724
dw0 -0.196611933241
dx0 0.393223866483


In [32]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
def dsigmoid(z):
    return (1 - z) * z

x = 3
y = -4

# forward
sigy = sigmoid(y)
num = x + sigy
sigx = sigmoid(x)
xpy = x + y
xpysqr = xpy ** 2
den = sigx + xpysqr
invden = 1.0/den      #(7)
f = num * invden      #(8)


# backward
df = 1
dnum = invden                        #(8)
dinvden = num                        #(8)
dden = dinvden * (-1.0 /(den ** 2))  #(7)
dsigx = dden
dxpysqr = dden
dxpy = (2 * xpy) * dxpysqr
dx = (1) * dxpy
dy = (1) * dxpy
dx += dsigmoid(x) * dsigx
dx += (1) * dnum
dsigy = (1) * dnum
dy += dsigmoid(y) * dsigy






In [33]:
x = 3
y = -4

# forward
sigy = 1.0 / (1 + np.exp(-y))
num = x + sigy
sigx = 1.0 / (1 + np.exp(-x))
xpy = x + y
xpysqr = xpy ** 2
den = sigx + xpysqr
invden = 1.0 / den
f = num * invden

# backward
df = 1
dnum = invden * df
dinvden = num * df
dden = (-1.0 / (den ** 2)) * dinvden
dsigx = (1) * dden
dxpysqr = (1) * dden
dxpy = (2 * xpy) * dxpysqr
dx = (1) * dxpy
dy = (1) * dxpy
dx += ((1 - x) * x) * dsigx
dx += (1) * dnum
dsigy = (1) * dnum
dy += ((1 - y) * y) * dsigy


In [ ]:

x = 3
y = -4

sigy = 1.0 / (1 + np.exp(-y))
num = x + sigy
sigx = 1.0 / (1 + np.exp(-x))
xpy = x + y
xpysqr = xpy ** 2
den = sigx + xpysqr
invden = 1.0 / den
f = num * invden

df = 1
dnum = invden * (df)
dinvden = num * (df)
dden = (-1.0 / (den ** 2)) * dinvden
dsigx = (1) * dden
dxpysqr = (1) * dden
dxpy = (2 * xpy) * dxpysqr
dx = (1) * dxpy
dy = (1) * dxpy
dx += ((1 - sigx) * sigx) * dsigx
dx += (1) * dnum
dsigy = (1) * dnum
dy += ((1 - sigy) * sigy) * dsigy



In [50]:
# forward pass
W = np.random.randn(5, 10)
X = np.random.randn(10, 3)
D = np.dot(W, X)

# print(*D.shape)
dD = np.random.randn(*D.shape)
dW = np.dot(dD, X.T)

print dD


[[ 0.10362292  0.87216744 -0.16097303]
 [-0.35192374 -1.09613071  0.14581964]
 [ 0.77591646 -0.29028436 -0.74626765]
 [-0.0439378  -0.90334797 -0.70964229]
 [-1.18734557  0.06296767 -0.98590201]]
