In [3]:
# Package imports
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import sklearn.datasets
import sklearn.linear_model
import matplotlib
import scipy.ndimage.filters

In [4]:
img = np.eye(8)
img = np.random.randn(4, 4)
print(img)
imgs = img[np.newaxis, np.newaxis, ...]
print(imgs)
filt = np.eye(7)
filts = filt[np.newaxis, np.newaxis, ...]
print filts
convout = np.empty_like(imgs)
print convout
print scipy.ndimage.filters.convolve(img, filt, mode='constant')


[[-1.0628376   0.55565456 -1.55260479  1.36307131]
 [-2.17526006 -1.36231805 -0.62845152  0.42024021]
 [ 1.33189327  0.50178419 -1.34640574  1.05913682]
 [-1.40847759 -0.45438191  1.58337408 -0.5977421 ]]
[[[[-1.0628376   0.55565456 -1.55260479  1.36307131]
   [-2.17526006 -1.36231805 -0.62845152  0.42024021]
   [ 1.33189327  0.50178419 -1.34640574  1.05913682]
   [-1.40847759 -0.45438191  1.58337408 -0.5977421 ]]]]
[[[[ 1.  0.  0.  0.  0.  0.  0.]
   [ 0.  1.  0.  0.  0.  0.  0.]
   [ 0.  0.  1.  0.  0.  0.  0.]
   [ 0.  0.  0.  1.  0.  0.  0.]
   [ 0.  0.  0.  0.  1.  0.  0.]
   [ 0.  0.  0.  0.  0.  1.  0.]
   [ 0.  0.  0.  0.  0.  0.  1.]]]]
[[[[-1.0628376   0.55565456 -1.55260479  1.36307131]
   [-2.17526006 -1.36231805 -0.62845152  0.42024021]
   [ 1.33189327  0.50178419 -1.34640574  1.05913682]
   [-1.40847759 -0.45438191  1.58337408 -0.5977421 ]]]]
[[-4.36930349  0.98633986 -1.13236458  1.36307131]
 [-0.0901018  -4.36930349  0.98633986 -1.13236458]
 [ 0.87751136 -0.0901018  -4.

In [5]:
img_h = img.shape[0]
img_w = img.shape[0]

filt_h = filt.shape[0]
filt_w = filt.shape[1]

filt_mid_h = filt_h // 2
filt_mid_w = filt_w // 2

for y in range(img_h):
#     print(-y, -filt_mid_h)
#     print max(-y, -filt_mid_h)
#     print(img_h - y, filt_mid_h+1)
    y_off_min = max(-y, -filt_mid_h)
    y_off_max = min(img_h-y, filt_mid_h+1)
#     print(y_off_min, y_off_max)

    for y_off in range(y_off_min, y_off_max):
#         print y_off
        img_y = y + y_off
        filt_y = filt_mid_w + y_off
        print(img_y, filt_y)
        


# for x in range(img_w):
#         x_off_min = max(-x, -filt_mid_w)
#         x_off_max = min(img_w-x, filt_mid_w+1)
#         print(x_off_min, x_off_max)    

    

(0, 3)
(1, 4)
(2, 5)
(3, 6)
(0, 2)
(1, 3)
(2, 4)
(3, 5)
(0, 1)
(1, 2)
(2, 3)
(3, 4)
(0, 0)
(1, 1)
(2, 2)
(3, 3)
