In [229]:
# Package imports
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import sklearn.datasets
import sklearn.linear_model
import matplotlib
import scipy.ndimage.filters

# Display plots inline and change default figure size
%matplotlib inline
matplotlib.rcParams['figure.figsize'] = (10.0, 8.0)

In [271]:

rand = np.random.RandomState(12)
# print rand.rand(2,2)

X = rand.rand(4,4)
print X
filt = rand.rand(3,3)
print filt

X[0:3,0:3]

X1 = X[0:3,0:3]
X2 = X[1:4,1:4]

print X1
print X2


[[ 0.15416284  0.7400497   0.26331502  0.53373939]
 [ 0.01457496  0.91874701  0.90071485  0.03342143]
 [ 0.95694934  0.13720932  0.28382835  0.60608318]
 [ 0.94422514  0.85273554  0.00225923  0.52122603]]
[[ 0.55203763  0.48537741  0.76813415]
 [ 0.16071675  0.76456045  0.0208098 ]
 [ 0.13521018  0.11627302  0.30989758]]
[[ 0.15416284  0.7400497   0.26331502]
 [ 0.01457496  0.91874701  0.90071485]
 [ 0.95694934  0.13720932  0.28382835]]
[[ 0.91874701  0.90071485  0.03342143]
 [ 0.13720932  0.28382835  0.60608318]
 [ 0.85273554  0.00225923  0.52122603]]


In [231]:
print X1
print X1.sum()
print X1.mean()

[[ 0.15416284  0.7400497   0.26331502]
 [ 0.01457496  0.91874701  0.90071485]
 [ 0.95694934  0.13720932  0.28382835]]
4.36955138937
0.48550570993


In [305]:
# forward
# B1 = (X1 * filt)
# B1_probs = (B1 / B1.sum())

# C1 = B1.sum()
# print C1

def convolute(X, filt):
    B = (X * filt)
    B_probs = (B / B.sum())
    C = B.sum()
    return C, B_probs
    

def get_filter(C, B_probs, X):
    return (C * B_probs) / X


def cost_func(X, B_probs, C, filt):
    return ((X - (C * B_probs / filt)) ** 2).sum()
    

C1, B1_probs = convolute(X1, filt)
print C1

1.60339286905


In [242]:
# backward
Z1 = (C1) * B1_probs / filt
print X1 - Z1

[[  0.00000000e+00   0.00000000e+00   5.55111512e-17]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00]]


In [266]:
rand = np.random.RandomState(12)
C2 = rand.rand()
# print C2
# Z2 = C2 * B1_probs / filt
# print Z2
print X1.sum()

    

# filt2 = (C2 * B1_probs) / X1
filt2 = get_filter(C2, B1_probs, X1)
Z2 = C2 * B1_probs / filt2

print Z2.sum()

# # filt2 = filt + 0.5
# Z2 = C2 * B1_probs / filt2
# print Z2.sum()


4.36955138937
4.36955138937


In [276]:
C1, B1_probs = convolute(X1, filt)
C2, B2_probs = convolute(X2, filt)

In [278]:
print C1
print C2

1.60339286905
1.49879784821


In [291]:
print get_filter(C1, B1_probs, X1)
print get_filter(C2, B2_probs, X2)

[[ 0.55203763  0.48537741  0.76813415]
 [ 0.16071675  0.76456045  0.0208098 ]
 [ 0.13521018  0.11627302  0.30989758]]
[[ 0.55203763  0.48537741  0.76813415]
 [ 0.16071675  0.76456045  0.0208098 ]
 [ 0.13521018  0.11627302  0.30989758]]


In [292]:
print filt

[[ 0.55203763  0.48537741  0.76813415]
 [ 0.16071675  0.76456045  0.0208098 ]
 [ 0.13521018  0.11627302  0.30989758]]


In [294]:
C3 = 1.12
C4 = 0.3

filt3 = get_filter(C3, B1_probs, X1)
filt4 = get_filter(C4, B2_probs, X2)

In [318]:
print C3 * filt3
print X1
# print ((X1 - (C3 * B1_probs / filt3)) ** 2).sum()
# print ((X2 - (C4 * B2_probs / filt4)) ** 2).sum()

filt5 = (filt3 + filt4) / 2
cost1 = cost_func(X1, B1_probs, C3, filt3)
cost2 = cost_func(X2, B2_probs, C4, filt3)
print cost1 + cost2



[[ 0.43188168  0.37973066  0.60094285]
 [ 0.12573531  0.598147    0.01628036]
 [ 0.10578047  0.09096515  0.24244559]]
[[ 0.15416284  0.7400497   0.26331502]
 [ 0.01457496  0.91874701  0.90071485]
 [ 0.95694934  0.13720932  0.28382835]]
1.58916427786
