https://grzegorzgwardys.wordpress.com/2016/04/22/8/#unique-identifier

In [1]:
import numpy as np

In [4]:
X = np.array([
        [1,2,3],
        [4,5,6],
        [7,8,9],
    ])

kernel = np.array([
        [-1,0],
        [ 1,2]
    ])

print X
print kernel

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1  0]
 [ 1  2]]


In [58]:
print (X[0:2,0:2] * kernel).sum()
print (X[0:2,1:3] * kernel).sum()
print (X[1:3,0:2] * kernel).sum()
print (X[1:3,1:3] * kernel).sum()

O = np.array([
        [13, 15],
        [19, 21],
    ])


13
15
19
21


In [31]:
# O.T
def rot180(X):
    return np.rot90(np.rot90(X))

kernel_rot = rot180(kernel)
print kernel_rot

[[ 2  1]
 [ 0 -1]]


In [84]:

print (kernel[1,1] * O[0,0]).sum()
print (kernel[1,:] * O[0,:]).sum()
print (kernel[1,0] * O[0,1]).sum()


print (kernel[:,1] * O[:,0]).sum()
print (kernel[:,:] * O[:,:]).sum()
print (kernel[:,0] * O[:,1]).sum()


print (kernel[0,1] * O[1,0]).sum()
print (kernel[0,:] * O[1,:]).sum()
print (kernel[0,0] * O[1,1]).sum()

grad = np.array([
        [26, 43, 15],
        [38, 48,  6],
        [ 0,-19,-21],
    ])

# print 0.001 * grad

print X + 0.001 * grad


26
43
15
38
48
6
0
-19
-21
[[ 1.026  2.043  3.015]
 [ 4.038  5.048  6.006]
 [ 7.     7.981  8.979]]
